cargo bench
cargo bench --features "copy"
cargo bench --features "tree"
cargo bench --features "check-mt"
cargo bench --features "copy tree"
cargo bench --features "copy check-mt"
cargo bench --features "copy tree check-mt"
cargo bench --features "tree check-mt"

cargo bench --features "en"
cargo bench --features "en copy"
cargo bench --features "en tree"
cargo bench --features "en check-mt"
cargo bench --features "en copy tree"
cargo bench --features "en copy check-mt"
cargo bench --features "en copy tree check-mt"
cargo bench --features "en tree check-mt"

cargo bench --features "br"
cargo bench --features "br copy"
cargo bench --features "br tree"
cargo bench --features "br check-mt"
cargo bench --features "br copy tree"
cargo bench --features "br copy check-mt"
cargo bench --features "br copy tree check-mt"
cargo bench --features "br tree check-mt"