cargo clippy
cargo clippy --features "copy"
cargo clippy --features "tree"
cargo clippy --features "check-mt"
cargo clippy --features "copy tree"
cargo clippy --features "copy check-mt"
cargo clippy --features "copy tree check-mt"
cargo clippy --features "tree check-mt"

cargo clippy --features "en"
cargo clippy --features "en colored"
cargo clippy --features "en copy"
cargo clippy --features "en colored copy"
cargo clippy --features "en tree"
cargo clippy --features "en colored tree"
cargo clippy --features "en check-mt"
cargo clippy --features "en colored check-mt"
cargo clippy --features "en copy tree"
cargo clippy --features "en colored copy tree"
cargo clippy --features "en copy check-mt"
cargo clippy --features "en colored copy check-mt"
cargo clippy --features "en copy tree check-mt"
cargo clippy --features "en colored copy tree check-mt"
cargo clippy --features "en tree check-mt"
cargo clippy --features "en colored tree check-mt"

cargo clippy --features "br"
cargo clippy --features "br colored"
cargo clippy --features "br copy"
cargo clippy --features "br colored copy"
cargo clippy --features "br tree"
cargo clippy --features "br colored tree"
cargo clippy --features "br check-mt"
cargo clippy --features "br colored check-mt"
cargo clippy --features "br copy tree"
cargo clippy --features "br colored copy tree"
cargo clippy --features "br copy check-mt"
cargo clippy --features "br colored copy check-mt"
cargo clippy --features "br copy tree check-mt"
cargo clippy --features "br colored copy tree check-mt"
cargo clippy --features "br tree check-mt"
cargo clippy --features "br colored tree check-mt"
