cargo test
cargo test --features "copy"
cargo test --features "tree"
cargo test --features "check-mt"
cargo test --features "copy tree"
cargo test --features "copy check-mt"
cargo test --features "copy tree check-mt"
cargo test --features "tree check-mt"

cargo test --features "en"
cargo test --features "en copy"
cargo test --features "en tree"
cargo test --features "en check-mt"
cargo test --features "en copy tree"
cargo test --features "en copy check-mt"
cargo test --features "en copy tree check-mt"
cargo test --features "en tree check-mt"

cargo test --features "br"
cargo test --features "br copy"
cargo test --features "br tree"
cargo test --features "br check-mt"
cargo test --features "br copy tree"
cargo test --features "br copy check-mt"
cargo test --features "br copy tree check-mt"
cargo test --features "br tree check-mt"